name: CICD

on:
  push:
    branches: [ NoDocker ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: yarn install
    - run: CI=false yarn build
    - name: ssh deploy on aws ec2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ~/home/ubuntu/noDocker
          yarn install
          yarn build
          yarn add serve
          serve -p 3000 build/