name: CICD

on:
  push:
    branches: [ NoDocker ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: yarn install
    - run: CI=false yarn build
    - name: ssh deploy on aws ec2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "./"
        TARGET: ${{ secrets.DEPLOY_TARGET }}