name: CICD

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          repository: RichardDavidKaavalan/CICD-TEST
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Configure Git for pushing to your repository
          run: |
            git remote add CICD-REPO https://github.com/RichardDavidKaavalan/CICD-TEST.git
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull CICD-REPO main
          git add .
          git commit -m "Sync from other-repo"
          git push origin main
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t richard1301808/git_cicd .
      - name: Publish image to docker hub
        run: docker push richard1301808/git_cicd:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: docker pull richard1301808/git_cicd:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer richard1301808/git_cicd
