name: Trigger Git Test Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-git-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch repository dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: RichardDavidKaavalan/git_test
          event-type: trigger-event
          client-payload: '{"branch": "dev"}'