name: Sync Dev to Git_Test Main

on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Remote Repository
        run: git remote add git_test https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/RichardDavidKaavalan/git_test.git
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Push to Git_Test Main Branch
        run: |
          git checkout -b temp-branch
          git push git_test temp-branch:main --force
