name: Trigger Git Test Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-git-test:
    if: github.repository == 'RichardDavidKaavalan/CICD-TEST'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push to Another Repository
        run: |
          git remote add other_repo https://github.com/RichardDavidKaavalan/git_test.git
          git push other_repo main
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Dispatch repository dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: RichardDavidKaavalan/git_test
          event-type: trigger-event
          client-payload: '{"branch": "dev"}'