name: Receive Trigger Event

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print payload
        run: |
          echo "Received repository dispatch event with payload:"
          echo "${{ toJson(github.event.client_payload) }}"
